In [1]:
import numpy as np

In [2]:
a = np.array([[1, 2, 3], [2, 5, 6], [6, 7, 4]])
print("Matrix:\n", a)

Matrix:
 [[1 2 3]
 [2 5 6]
 [6 7 4]]


In [3]:
b = np.eye(5)
print("Identical matrix:\n", b)

Identical matrix:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [4]:
c = np.ones((7, 5))
print("Matrix with ones:\n", c)

Matrix with ones:
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [5]:
v = np.arange(0, 24, 2)
print("column vector:\n", v)

column vector:
 [ 0  2  4  6  8 10 12 14 16 18 20 22]


In [6]:
d = v.reshape((3, 4))
print("Matrix:\n", d)

Matrix:
 [[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]]


In [8]:
print("Second elemnet of the third raw:", d[2, 1])

Second elemnet of the third raw: 18


In [10]:
print("Second line:\n", d[1, :])
print("Fourth column:\n", d[:, 3])

Second line:
 [ 8 10 12 14]
Fourth column:
 [ 6 14 22]


In [11]:
print("Elements with coordinates (1, 2) and (0, 3):\n", d[[1, 0], [2, 3]])

Elements with coordinates (1, 2) and (0, 3):
 [12  6]


In [12]:
a = np.array([1, 2, 3])
b = np.array([[1], [2], [3]])

In [13]:
print("Vector:\n", a)
print("it's shape:\n", a.shape)
print("2d array:\n", b)
print("it's shape:\n", b.shape)

Vector:
 [1 2 3]
it's shape:
 (3,)
2d array:
 [[1]
 [2]
 [3]]
it's shape:
 (3, 1)


In [14]:
a = a.T
b = b.T

In [15]:
print("Vector has not changed:\n", a)
print("It's shape also has not changed:\n", a.shape)
print("Transposed 2d array:\n", b)
print("It's shape has changed:\n", b.shape)

Vector has not changed:
 [1 2 3]
It's shape also has not changed:
 (3,)
Transposed 2d array:
 [[1 2 3]]
It's shape has changed:
 (1, 3)


In [16]:
a = np.array([[1, 0], [0, 1]])
b = np.array([[4, 1], [2, 2]])
r1 = np.dot(a, b)
r2 = a.dot(b)
r3 = a@b

In [17]:
print("Matrix A:\n", a)
print("Matrix B:\n", b)
print("Multiplication with dot(a,b):\n", r1)
print("Multiplication with a.dot(b):\n", r2)
print("Multiplication with @:\n", r3)

Matrix A:
 [[1 0]
 [0 1]]
Matrix B:
 [[4 1]
 [2 2]]
Multiplication with dot(a,b):
 [[4 1]
 [2 2]]
Multiplication with a.dot(b):
 [[4 1]
 [2 2]]
Multiplication with @:
 [[4 1]
 [2 2]]


In [18]:
c = np.array([1, 2])
r3 = b.dot(c)

In [19]:
print("Matrix:\n", b)
print("Vector:\n", c)
print("Multiplication result:\n", r3)

Matrix:
 [[4 1]
 [2 2]]
Vector:
 [1 2]
Multiplication result:
 [6 6]


In [20]:
r = a * b

In [21]:
print("Matrix A:\n", a)
print("Matrix B:\n", b)
print("Multiplication with *:\n", r)

Matrix A:
 [[1 0]
 [0 1]]
Matrix B:
 [[4 1]
 [2 2]]
Multiplication with *:
 [[4 0]
 [0 2]]


In [22]:
a = np.array([[1, 2], [3, 4]])
b = np.transpose(a)
c = a.T

In [23]:
print("Matrix:\n", a)
print("Transposed with function:\n", b)
print("Transposed with method:\n",  c)

Matrix:
 [[1 2]
 [3 4]]
Transposed with function:
 [[1 3]
 [2 4]]
Transposed with method:
 [[1 3]
 [2 4]]


In [24]:
a = np.array([[1, 2, 1], [1, 1, 4], [2, 3, 6]], dtype=np.float32)
det = np.linalg.det(a)

In [25]:
print("Matrix:\n", a)
print("Determinant:\n", det)

Matrix:
 [[1. 2. 1.]
 [1. 1. 4.]
 [2. 3. 6.]]
Determinant:
 -1.0


In [26]:
a = np.array([[1, 2, 3], [1, 1, 1], [2, 2, 2]])
r = np.linalg.matrix_rank(a)

In [27]:
print("Matrix:\n", a)
print("Matrix rank:", r)

Matrix:
 [[1 2 3]
 [1 1 1]
 [2 2 2]]
Matrix rank: 2


In [28]:
a = np.array([1, 2, 3])
b = np.array([1, 1, 1])
c = np.array([2, 3, 5])
m = np.array([a, b, c])

In [29]:
print(np.linalg.matrix_rank(m) == m.shape[0])

True


In [30]:
a = np.array([[3, 1], [1, 2]])
b = np.array([9, 8])
x = np.linalg.solve(a, b)

In [31]:
print("Matrix A:\n", a)
print("Vector b:\n", b)
print("Solution :\n", x)

Matrix A:
 [[3 1]
 [1 2]]
Vector b:
 [9 8]
Solution :
 [2. 3.]


In [32]:
print(a.dot(x))

[9. 8.]


In [33]:
a = np.array([[1, 2, 1], [1, 1, 4], [2, 3, 6]], dtype=np.float32)
b = np.linalg.inv(a)

In [34]:
print("Matrix A:\n", a)
print("Inversed Matrix A:\n", b)
print("Multiplication of inversed A and A:\n", a.dot(b))

Matrix A:
 [[1. 2. 1.]
 [1. 1. 4.]
 [2. 3. 6.]]
Inversed Matrix A:
 [[ 6.  9. -7.]
 [-2. -4.  3.]
 [-1. -1.  1.]]
Multiplication of inversed A and A:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [35]:
a = np.array([[-1, -6], [2, 6]])
w, v = np.linalg.eig(a)

In [37]:
print("Matrix A:\n", a)
print("Eigenvalue:\n", w)
print("Eigenvector:\n", v)

Matrix A:
 [[-1 -6]
 [ 2  6]]
Eigenvalue:
 [2. 3.]
Eigenvector:
 [[-0.89442719  0.83205029]
 [ 0.4472136  -0.5547002 ]]


In [42]:
a@v[:,0],  w[0]*v[:,0]

(array([-1.78885438,  0.89442719]), array([-1.78885438,  0.89442719]))